version: '3'
services:
 web:
  container_name: web
  build: 
    context: .
    dockerfile: Dockerfile.dev
  working_dir: /app
  volumes:
   - /app/node_modules
   - .:/app
  

 nginx:
  image: nginx:alpine
  volumes:
    # - ./build:/usr/share/nginx/html
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  ports:
    - 5000:80
    

